### ISSUE TITLE
Support for Ai Stitching

### ISSUE THREAD

**Issue by 1661410107114145152525** [MantisSub/batchstitcher#2]
Dear MantisSub-Team,

I really love your Batch Stitcher a lot! In it's latest version (on the official download page) Insta360 added Ai Stitching and batch stitching for videos (far not as convenient as yours and as always super confusing with settings that reset etc.) so I would still preferrably use your stitcher. Am I overseeing something or is this version not folly supported, if so: 'ould you update your amazing tool so that it supports the latest Insta360 Stitcher version fully (mainly the stitching options, since Ai Stitching provides far better results in specific use cases).

Thank you very much for providing this great free tool!

**Comment by xlvisuals** [comment]
Thank you, I'm glad you like the Batch Stitcher. Sorry, there's no further development scheduled at the moment. You're welcome to submit a pull request or fork the project.
