### ISSUE TITLE
Improving encoding performance for PC

### ISSUE THREAD

**Issue by 1661410107114145152525** [MantisSub/batchstitcher#3]
Dear MantisSub-Team,

as I already said I really like your software a lot and am so glad you offer it for free.

Anyway there is a huge problem that I have with Insta360 Stitcher that hopefully your custom solution could fix. I recently compared the different output formats quality-wise and Prores outperforms e.g. H265 at max. bitrate by far (especially in darker areas many details are lost in H265). Furthermore it is best practice to only render out the final edited video in a format that sacrifices some quality for conpresssion since you will loose too much quality when reencoding too often. Sadly Insta360 Stitcher only supports prores as "lossless" format. Prores increases rendering times even on an RTX4090 High-End PC a lot since it does not support GPU rendering in Insta360. Is there any possibility that you add a comparable lossless codec that can use the GPU or even better has hardware encoding support (I guess the last one is pretty uncommon for such codecs but using the GPU would already move the bottleneck away from the CPU)? Or as an alternative offer higher bitrate exports for e.g. H265 or so, that it becomes "lossless"... (I edit with proxies later on anyways so that shouldn't be a problem)

Thanks a lot in advance for your help - have a great day! :)

**Comment by xlvisuals** [comment]
The Batch Stitcher is basically just a different front-end for Insta360 stitcher, we're not providing our own stitching code. So sorry we can't speed it up or provide further codecs.
